package com.myspace.kafkaread;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class kafkaContext implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public kafkaContext() {
    }




}